version: "3.8"

services:
  # RabbitMQ
  rabbit:
    hostname: rabbit
    image: rabbitmq:3.10.0-rc.3-management
    env_file: .env
    ports:
      - "5672:5672" # we forward this port because it's useful for debugging
      - "15672:15672" # here, we can access rabbitmq management plugin
    networks:
      - main

  admin-backend:
    image: sudiptob2/microserve-admin
    command: "bash scripts/backend_entrypoint.sh"
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - admin-db
      - rabbit

    networks:
      - main

  admin-db:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - "5411:5432"
    networks:
      - main

  admin-queue:
    image: sudiptob2/microserve-admin
    env_file:
      - .env
    command: "python -u consumer.py"
    depends_on:
      - admin-db
      - rabbit
    restart: always
    networks:
      - main

  main-backend:
    image: sudiptob2/microserve-main
    env_file:
      - .env
    command: "bash scripts/entrypoint.sh"
    ports:
      - 8001:5000
    depends_on:
      - main-db
      - rabbit
    restart: unless-stopped
    networks:
      - main

  main-queue:
    image: sudiptob2/microserve-main
    env_file:
      - .env
    command: "python -u consumer.py"
    depends_on:
      - main-db
      - rabbit
    restart: always
    networks:
      - main

  main-db:
    image: mysql:5.7.22
    restart: always
    env_file:
      - .env
    volumes:
      - msql-data:/var/lib/mysql
    ports:
      - 33062:3306
    networks:
      - main

volumes:
  pg-data:
  msql-data:

networks:
  main:
